"""WAN-path evidence: name the hop where the path broke (PERF-7).

A district lost its internet over roughly a week and NetMon never said what
broke. The signal that looked like proof — ~47% of speed tests returning
0.0 Mbps — turned out to be Cloudflare rate-limiting our own probe (three
sensors behind one egress IP, HTTP 429). After PERF-2's honesty fix removed
that false signal, nothing remained that explained the outage.

This module captures the evidence that does: a bounded ladder run ON the sensor,
autonomously, at the moment the path is broken. It answers three questions in
order, and is careful about which of them it can actually answer:

  1. Is the sensor's own LAN alive?      (gateway ping)
  2. Can we open a NEW TCP session out?  (connect to :443 — the authoritative fact)
  3. Where does the path stop?           (traceroute, ICMP + TCP, vs a baseline)

WHY A TCP CONNECT IS THE VERDICT AND TRACEROUTE IS ONLY CORROBORATION
---------------------------------------------------------------------
A ping-based trigger misreads the case this exists for. In the stateful-firewall
failure, ICMP keeps flowing while NEW TCP sessions die — ping says "fine" while
every user says "the internet is down". So the verdict is driven by whether a
TCP handshake to :443 completes. That is binary, fast, and unambiguous.

Traceroute cannot carry the verdict, because on a real school network it lies in
both directions. Measured on a HEALTHY production sensor (Monitor1, 2026-09-05):

  * `traceroute -T -p 443 --sport=33434 1.1.1.1` — the fixed-flow form, which is
    the textbook recommendation for stable ECMP — returned hops 1-3 then STARS to
    the limit, taking 18s. Byte-identical to a genuinely unroutable address.
    Meanwhile a plain TCP connect to 1.1.1.1:443 succeeded in 15ms. Pinning the
    source port makes every probe one 5-tuple, and the on-path stateful device
    treats the repeated low-TTL SYNs as retransmits of a single half-open flow
    and stops eliciting replies. So the "fixed flow" advice inverts here: it
    manufactures a total-blackout reading on a perfectly healthy path.
  * Without `--sport`, the same trace mapped all 11 hops in 0.06s.

Hence: NO `--sport`. The ECMP instability that `--sport` is meant to solve is
real but small and LOCALISED — across four consecutive healthy runs, hops 1-4
and 6-9 were byte-identical every time; only hop 5 (CENIC) and hop 10
(Cloudflare) flapped between a handful of addresses. So we absorb ECMP in the
BASELINE instead of in the probe: the baseline records, per hop index, the SET of
addresses ever seen there. A hop that flaps accumulates its alternatives and
stops being interesting; a hop that is genuinely stable keeps exactly one.

WHAT THE HOP TABLE DOES AND DOESN'T PROVE
-----------------------------------------
For a failing edge device the hops bracket the break to "between our inside
interface and the first ISP hop" — they corroborate, they do not conclude. Two
rules keep it honest:

  * A star followed by a LATER responding hop is an artifact, not a break:
    routers rate-limit ICMP generated by their own control plane. Only a
    TRAILING run of stars marks where the path stops (`last_responding_hop`).
  * A path that ends in stars is only a FINDING when the baseline for this site
    got further. Plenty of healthy paths end in stars (the last hop before the
    dashboard does, in production). Without a baseline the reading is noise,
    which is why the baseline is load-bearing here rather than a refinement.

Everything is bounded: per-probe timeouts, a hop cap, and a wall-clock ceiling
that abandons remaining traces rather than overrunning. Nothing here takes
caller-supplied arguments — targets come from validated pushed config — so the
sensor's fixed-argv containment model is preserved.
"""
from __future__ import annotations

import json
import re
import shutil
import socket
import subprocess
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger(__name__)

# State lives beside the other sensor state, outside the repo.
WAN_PATH_DIR = Path("/var/lib/netmon/wan-path")
BASELINE_FILE = WAN_PATH_DIR / "baseline.json"
STATE_FILE = WAN_PATH_DIR / "state.json"
CAPTURE_DIR = WAN_PATH_DIR / "captures"

# Captures are small (~2-6 KB). 300 covers a multi-day incident at the 15-minute
# degraded cadence with room for the daily baselines either side of it.
CAPTURE_MAX = 300

# Traceroute bounds. 15 hops reaches the dashboard (measured: 15 hops to
# netmon.sbcss.net) without paying for a long walk to nowhere; -w 2 is the
# per-probe wait, -q 1 one query per hop (the baseline's repeat samples give us
# redundancy more cheaply than -q 3 does).
TRACE_MAX_HOPS = 15
TRACE_WAIT_SEC = 2
# Worst case per trace is roughly max_hops * wait when every hop stars out; the
# subprocess timeout has to clear that or we'd kill our own evidence.
TRACE_TIMEOUT_SEC = TRACE_MAX_HOPS * TRACE_WAIT_SEC + 15

# Whole-capture ceiling. Past this we stop starting new traces and report what we
# have — a partial capture delivered is worth more than a complete one killed by
# the watchdog mid-write.
CAPTURE_BUDGET_SEC = 150

# How many traces per mode a baseline refresh takes, to learn the ECMP sets.
# Four runs was enough on Monitor1 to expose both flapping hops.
BASELINE_SAMPLES = 4

_IPV4 = re.compile(r"\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b")
_HOP_LINE = re.compile(r"^\s*(\d+)\s+(.*)$")
_FLOAT_MS = re.compile(r"([\d.]+)\s*ms")
_LOSS = re.compile(r"(\d+(?:\.\d+)?)%\s*packet loss")
_RTT_AVG = re.compile(r"=\s*[\d.]+/([\d.]+)/")


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


# ---------------------------------------------------------------------------
# TCP reachability — the authoritative control
# ---------------------------------------------------------------------------


def targets_from(settings: Any) -> list[str]:
    """Parse the configured control targets, keeping only IP LITERALS.

    Two reasons this is a hard filter and not a nicety:
      * The first target is passed to `traceroute` as its destination argument,
        and traceroute parses options wherever they appear — so a pushed value
        like "--help", or anything leading with '-', would become an OPTION
        rather than a destination. An `ip_address()` parse makes that
        structurally impossible, which is stronger than a character blocklist
        (the failure mode a previous fix on this box already had to unlearn:
        `splitlines()` splits on ten characters, not the three you thought of).
      * A control target that needed DNS could not distinguish a dead resolver
        from a dead circuit — a distinction this feature exists to make.
    """
    import ipaddress

    out: list[str] = []
    for raw in str(getattr(settings, "wan_path_targets", "") or "").split(","):
        cand = raw.strip()
        if not cand:
            continue
        try:
            ipaddress.ip_address(cand)
        except ValueError:
            log.warning("wan-path target is not an IP literal; ignoring", target=cand)
            continue
        if cand not in out:
            out.append(cand)
    return out


def tcp_connect(host: str, port: int = 443, timeout: float = 5.0) -> dict[str, Any]:
    """Open and immediately close a TCP session. Returns {ok, ms, error}.

    This is the control the whole ladder turns on, so it deliberately measures
    the HANDSHAKE and nothing above it. We do not send an HTTP request: an
    application-layer answer of ANY kind (200, 403, and notably 429 — the
    rate-limit that produced eight days of phantom evidence) already proves the
    path works, so folding HTTP in could only add ways to misread a working path
    as a broken one. A completed three-way handshake is the fact we want.
    """
    started = time.monotonic()
    try:
        with socket.create_connection((host, port), timeout=timeout):
            pass
    except OSError as exc:
        # strerror alone is often empty for timeouts; str(exc) carries the reason.
        return {
            "target": host,
            "port": port,
            "ok": False,
            "ms": round((time.monotonic() - started) * 1000, 1),
            "error": str(exc)[:200] or exc.__class__.__name__,
        }
    return {
        "target": host,
        "port": port,
        "ok": True,
        "ms": round((time.monotonic() - started) * 1000, 1),
        "error": None,
    }


def dns_resolves(name: str, timeout: float = 5.0) -> dict[str, Any]:
    """Resolve a name to prove the resolver works.

    Kept separate from the TCP controls, which use IP literals precisely so that
    a dead resolver cannot masquerade as a dead WAN. If the literals connect and
    this fails, the finding is DNS, not the circuit.
    """
    started = time.monotonic()
    prior = socket.getdefaulttimeout()
    try:
        socket.setdefaulttimeout(timeout)
        socket.getaddrinfo(name, 443, proto=socket.IPPROTO_TCP)
    except OSError as exc:
        return {"name": name, "ok": False,
                "ms": round((time.monotonic() - started) * 1000, 1),
                "error": str(exc)[:200] or exc.__class__.__name__}
    finally:
        socket.setdefaulttimeout(prior)
    return {"name": name, "ok": True,
            "ms": round((time.monotonic() - started) * 1000, 1), "error": None}


def ping(host: str, count: int = 3, timeout: int = 2) -> dict[str, Any]:
    """Small ICMP sample. Best-effort; never raises."""
    cmd = ["ping", "-n", "-c", str(count), "-W", str(timeout), host]
    try:
        res = subprocess.run(
            cmd, capture_output=True, text=True, timeout=count * timeout + 5, check=False
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        return {"target": host, "alive": False, "rtt_ms": None, "loss_pct": 100.0,
                "error": str(exc)[:200] or "ping failed"}
    text = (res.stdout or "") + (res.stderr or "")
    loss: float | None = None
    m = _LOSS.search(text)
    if m:
        try:
            loss = float(m.group(1))
        except ValueError:
            loss = None
    rtt: float | None = None
    m = _RTT_AVG.search(text)
    if m:
        try:
            rtt = float(m.group(1))
        except ValueError:
            rtt = None
    alive = res.returncode == 0 or (loss is not None and loss < 100)
    return {"target": host, "alive": alive, "rtt_ms": rtt,
            "loss_pct": loss if loss is not None else (0.0 if alive else 100.0),
            "error": None if alive else "no reply"}


# ---------------------------------------------------------------------------
# traceroute
# ---------------------------------------------------------------------------


def _trace_argv(dest: str, mode: str, max_hops: int, wait: int) -> list[str]:
    """Build the traceroute argv for a mode.

    NOTE the deliberate absence of `--sport`. See the module docstring: on a
    measured production path, pinning the source port turned a healthy 11-hop
    trace into hops 1-3 plus stars, in 18 seconds instead of 0.06.
    """
    argv = ["traceroute", "-n", "-m", str(max_hops), "-w", str(wait), "-q", "1"]
    if mode == "icmp":
        argv.append("-I")
    elif mode == "tcp443":
        argv += ["-T", "-p", "443"]
    else:  # pragma: no cover - guarded by the caller's fixed mode list
        raise ValueError(f"unknown traceroute mode {mode!r}")
    argv.append(dest)
    return argv


def trace(
    dest: str,
    mode: str = "icmp",
    *,
    max_hops: int = TRACE_MAX_HOPS,
    wait: int = TRACE_WAIT_SEC,
) -> dict[str, Any]:
    """Run one traceroute. Returns a structured path; never raises."""
    if not shutil.which("traceroute"):
        return {"mode": mode, "dest": dest, "hops": [], "reached_at": None,
                "last_responding_hop": None, "error": "traceroute not installed"}
    try:
        res = subprocess.run(
            _trace_argv(dest, mode, max_hops, wait),
            capture_output=True, text=True, timeout=TRACE_TIMEOUT_SEC, check=False,
        )
    except subprocess.TimeoutExpired:
        return {"mode": mode, "dest": dest, "hops": [], "reached_at": None,
                "last_responding_hop": None, "error": "traceroute timed out"}
    except (FileNotFoundError, OSError) as exc:
        return {"mode": mode, "dest": dest, "hops": [], "reached_at": None,
                "last_responding_hop": None, "error": str(exc)[:200]}

    hops = _parse_hops(res.stdout or "")
    reached_at = next((h["hop"] for h in hops if h["ip"] == dest), None)
    return {
        "mode": mode,
        "dest": dest,
        "hops": hops,
        "reached_at": reached_at,
        "last_responding_hop": last_responding_hop(hops),
        "error": None,
    }


def _parse_hops(stdout: str) -> list[dict[str, Any]]:
    """Parse traceroute -n output into [{hop, ip, rtt_ms}] (ip None for a star)."""
    hops: list[dict[str, Any]] = []
    for line in stdout.splitlines():
        m = _HOP_LINE.match(line)
        if not m:
            continue  # the "traceroute to ..." header
        rest = m.group(2)
        ipm = _IPV4.search(rest)
        msm = _FLOAT_MS.search(rest)
        rtt: float | None = None
        if msm:
            try:
                rtt = float(msm.group(1))
            except ValueError:
                rtt = None
        hops.append({"hop": int(m.group(1)),
                     "ip": ipm.group(1) if ipm else None,
                     "rtt_ms": rtt})
    return hops


def last_responding_hop(hops: list[dict[str, Any]]) -> int | None:
    """The last hop that answered, ignoring gaps that later hops close.

    Routers police ICMP generated by their own control plane, so an isolated
    star at hop k with a live hop k+1 says nothing about the path — hop k simply
    declined to speak. Only a run of stars extending to the END of the trace
    marks where forwarding actually stopped. Returns None if nothing answered.
    """
    last: int | None = None
    for h in hops:
        if h.get("ip"):
            last = h["hop"]
    return last


def trailing_star_count(hops: list[dict[str, Any]]) -> int:
    """How many consecutive non-answering hops close the trace."""
    n = 0
    for h in reversed(hops):
        if h.get("ip"):
            break
        n += 1
    return n


# ---------------------------------------------------------------------------
# Baseline: what this site's path looks like when it works
# ---------------------------------------------------------------------------


def empty_baseline() -> dict[str, Any]:
    return {"updated_at": None, "sample_count": 0, "modes": {}}


def merge_baseline(
    baseline: dict[str, Any], traces: list[dict[str, Any]]
) -> dict[str, Any]:
    """Fold healthy traces into the baseline, accumulating per-hop IP SETS.

    ECMP is absorbed here rather than in the probe. A hop that load-balances
    accrues its handful of alternatives over successive samples and thereafter
    matches any of them; a genuinely stable hop keeps exactly one address, so a
    substitution there stays a real signal. This is why one sample is not a
    baseline: on the measured path, hops 5 and 10 flap and would otherwise
    report a divergence on every single healthy run.
    """
    out: dict[str, Any] = {
        "updated_at": _now_iso(),
        "sample_count": int(baseline.get("sample_count") or 0),
        "modes": dict(baseline.get("modes") or {}),
    }
    for tr in traces:
        if tr.get("error") or not tr.get("hops"):
            continue
        mode = str(tr.get("mode"))
        entry = dict(out["modes"].get(mode) or {})
        # If the destination changed, the accumulated hops describe a path to
        # somewhere else. Merging into them would build a chimera — `dest` naming
        # the new target while `hop_ips` and `deepest_responding_hop` still hold
        # the old route — which then PASSES compare()'s destination check and
        # reports the difference between two unrelated paths as a break. Start
        # this mode's baseline over instead.
        if entry.get("dest") and entry["dest"] != tr.get("dest"):
            log.info("wan-path baseline reset: destination changed",
                     mode=mode, was=entry["dest"], now=tr.get("dest"))
            entry = {}
        entry["dest"] = tr.get("dest")
        hop_ips: dict[str, list[str]] = {
            str(k): list(v) for k, v in (entry.get("hop_ips") or {}).items()
        }
        for h in tr["hops"]:
            ip = h.get("ip")
            if not ip:
                continue
            key = str(h["hop"])
            seen = hop_ips.setdefault(key, [])
            if ip not in seen:
                seen.append(ip)
        entry["hop_ips"] = hop_ips
        # The deepest hop that has EVER answered. A capture that stops well short
        # of this is the finding; one that matches it is a normal end-of-path.
        deepest = max((int(k) for k in hop_ips), default=0)
        entry["deepest_responding_hop"] = max(
            int(entry.get("deepest_responding_hop") or 0), deepest
        )
        if tr.get("reached_at"):
            entry["reached_at"] = tr["reached_at"]
        out["modes"][mode] = entry
        out["sample_count"] += 1
    return out


def compare(baseline: dict[str, Any], tr: dict[str, Any]) -> dict[str, Any]:
    """Diff one trace against the baseline for its mode.

    Reports two distinct things, because they mean different things to an
    engineer: the path STOPPING EARLY (a break), and a hop being SUBSTITUTED (a
    reroute). Only the first is an outage signature.
    """
    mode = str(tr.get("mode"))
    entry = (baseline.get("modes") or {}).get(mode)
    # A baseline is only meaningful for the destination it was measured against.
    # Change `wan_path_targets` and the stored path is a path to somewhere else —
    # comparing against it manufactures a break out of a shorter route. Caught on
    # a live sensor: a capture aimed one hop away was headlined "the path stops
    # after hop 1" purely because the baseline had been built to 1.1.1.1, eleven
    # hops out. Fail closed and claim nothing until the baseline is rebuilt.
    if entry and entry.get("dest") and tr.get("dest") and entry["dest"] != tr["dest"]:
        entry = None
    if not entry:
        return {"mode": mode, "have_baseline": False, "short_by": None,
                "break_after_hop": None, "break_after_ip": None, "new_ips": []}

    hop_ips: dict[str, list[str]] = entry.get("hop_ips") or {}
    new_ips: list[dict[str, Any]] = []
    for h in tr.get("hops") or []:
        ip = h.get("ip")
        if not ip:
            continue
        known = hop_ips.get(str(h["hop"])) or []
        if known and ip not in known:
            new_ips.append({"hop": h["hop"], "ip": ip, "baseline": known})

    deepest_known = int(entry.get("deepest_responding_hop") or 0)
    last = tr.get("last_responding_hop")
    last_int = int(last) if last else 0
    # A trace that REACHED its destination did not break, however deep the
    # baseline happens to go. Without this, a route that legitimately shortened
    # (a closer anycast node, a restored direct path) reads as a failure — the
    # measurement arriving is the strongest possible evidence that it did not.
    if tr.get("reached_at"):
        short_by = None
    else:
        short_by = deepest_known - last_int if deepest_known > last_int else None

    break_after_ip = None
    if short_by:
        break_after_ip = next(
            (h.get("ip") for h in (tr.get("hops") or []) if h.get("hop") == last_int),
            None,
        )
    return {
        "mode": mode,
        "have_baseline": True,
        "baseline_deepest_hop": deepest_known,
        "short_by": short_by,
        "break_after_hop": last_int if short_by else None,
        "break_after_ip": break_after_ip,
        "new_ips": new_ips,
    }


# ---------------------------------------------------------------------------
# The ladder
# ---------------------------------------------------------------------------

# Verdict codes, most specific first. These are the operator-facing conclusions;
# each is a claim we can actually support from the measurements above.
VERDICT_OK = "ok"
VERDICT_LAN = "lan"
VERDICT_DNS = "dns"
VERDICT_TCP_BLOCKED = "tcp_blocked"
VERDICT_WAN_DOWN = "wan_down"
VERDICT_DASHBOARD_ONLY = "dashboard_only"

_VERDICT_TEXT = {
    VERDICT_OK: "the path is healthy from here",
    VERDICT_LAN: "the sensor's own gateway is not answering - this is a LAN-side "
                 "fault, and nothing beyond it can be diagnosed from this box",
    VERDICT_DNS: "name resolution is failing while direct IP connections still "
                 "work - the circuit is up, the resolver is not",
    VERDICT_TCP_BLOCKED: "ICMP crosses the path but NO new TCP session to :443 "
                         "completes - the signature of a stateful device dropping "
                         "new sessions (state table, licence, or policy), not a "
                         "dead circuit",
    VERDICT_WAN_DOWN: "no path to the internet: neither ICMP nor TCP reaches any "
                      "control target, while the local gateway still answers",
    VERDICT_DASHBOARD_ONLY: "the internet is reachable but the dashboard is not - "
                            "this is a dashboard-side or DNS-side fault, NOT a "
                            "site outage",
}


def decide(
    gateway: dict[str, Any] | None,
    controls: list[dict[str, Any]],
    dashboard_control: dict[str, Any] | None,
    dns: dict[str, Any] | None,
    icmp_internet_ok: bool,
) -> dict[str, Any]:
    """Turn the measurements into one supportable conclusion.

    Ordered most-specific first so a LAN fault is never reported as a WAN
    outage, and a dashboard outage is never reported as a site outage — that
    misattribution is the whole reason this exists.
    """
    if gateway is not None and not gateway.get("alive"):
        code = VERDICT_LAN
    elif controls and all(not c.get("ok") for c in controls):
        # Every independent internet control refused a new TCP session.
        code = VERDICT_TCP_BLOCKED if icmp_internet_ok else VERDICT_WAN_DOWN
    elif dns is not None and not dns.get("ok"):
        # IP literals connected (we are past the all-fail branch) but names do not
        # resolve. Distinct fault, distinct owner.
        code = VERDICT_DNS
    elif dashboard_control is not None and not dashboard_control.get("ok"):
        code = VERDICT_DASHBOARD_ONLY
    else:
        code = VERDICT_OK
    return {"code": code, "summary": _VERDICT_TEXT[code]}


def capture(
    *,
    reason: str,
    controls: list[str],
    dashboard_host: str | None = None,
    gateway_ip: str | None = None,
    dns_name: str = "cloudflare.com",
    trace_dest: str | None = None,
    baseline: dict[str, Any] | None = None,
    budget_sec: int = CAPTURE_BUDGET_SEC,
) -> dict[str, Any]:
    """Run the bounded evidence ladder and return one capture record.

    `controls` are IP LITERALS from validated config — never names, so a dead
    resolver cannot be mistaken for a dead circuit, and never caller argv.
    """
    started_mono = time.monotonic()
    rec: dict[str, Any] = {
        "startedAt": _now_iso(),
        "reason": reason,
        "gateway": None,
        "dns": None,
        "controls": [],
        "dashboardControl": None,
        "icmpInternetOk": False,
        "traces": [],
        "diffs": [],
        "verdict": None,
        "truncated": False,
        "elapsedMs": 0,
    }

    def _left() -> float:
        return budget_sec - (time.monotonic() - started_mono)

    if gateway_ip:
        rec["gateway"] = ping(gateway_ip)

    # TCP controls first: they are fast and they carry the verdict.
    for target in controls:
        rec["controls"].append(tcp_connect(target, 443))
    if dashboard_host:
        rec["dashboardControl"] = tcp_connect(dashboard_host, 443)

    rec["dns"] = dns_resolves(dns_name)

    # Does ICMP cross where TCP did not? This is the divergence that separates a
    # stateful-firewall failure from a dead circuit, and it is measured at the
    # CONNECT level (reliable) rather than read off traceroute (noisy).
    icmp_ok = False
    for target in controls:
        if _left() <= 0:
            rec["truncated"] = True
            break
        if ping(target, count=2, timeout=2).get("alive"):
            icmp_ok = True
            break
    rec["icmpInternetOk"] = icmp_ok

    dest = trace_dest or (controls[0] if controls else None)
    if dest:
        for mode in ("icmp", "tcp443"):
            # Each trace can cost ~max_hops*wait in the blackout case. Only start
            # one we can afford to finish; a partial capture beats a killed one.
            if _left() < TRACE_TIMEOUT_SEC:
                rec["truncated"] = True
                break
            tr = trace(dest, mode)
            rec["traces"].append(tr)
            if baseline:
                rec["diffs"].append(compare(baseline, tr))

    rec["verdict"] = decide(
        rec["gateway"], rec["controls"], rec["dashboardControl"],
        rec["dns"], icmp_ok,
    )
    # Attach the hop bracket to the verdict when the diff supports one, so the
    # headline can say WHERE without the reader assembling it.
    brk = next((d for d in rec["diffs"] if d.get("break_after_ip")), None)
    if brk:
        rec["verdict"]["breakAfterHop"] = brk["break_after_hop"]
        rec["verdict"]["breakAfterIp"] = brk["break_after_ip"]
    rec["elapsedMs"] = int((time.monotonic() - started_mono) * 1000)
    return rec


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


def _write_json(path: Path, doc: Any) -> None:
    """Atomic write — a partial file must never be read back as truth."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    tmp.replace(path)


def _read_json(path: Path, default: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 — missing/corrupt state is not fatal
        return default


def load_baseline() -> dict[str, Any]:
    doc = _read_json(BASELINE_FILE, None)
    return doc if isinstance(doc, dict) else empty_baseline()


def save_baseline(doc: dict[str, Any]) -> None:
    _write_json(BASELINE_FILE, doc)


def load_state() -> dict[str, Any]:
    doc = _read_json(STATE_FILE, None)
    return doc if isinstance(doc, dict) else {}


def save_state(doc: dict[str, Any]) -> None:
    _write_json(STATE_FILE, doc)


def save_capture(rec: dict[str, Any]) -> Path:
    """Persist a capture, evicting the OLDEST beyond the cap."""
    CAPTURE_DIR.mkdir(parents=True, exist_ok=True)
    existing = sorted(CAPTURE_DIR.glob("*.json"))
    for stale in existing[: max(0, len(existing) + 1 - CAPTURE_MAX)]:
        stale.unlink(missing_ok=True)
    path = CAPTURE_DIR / f"{time.time_ns():020d}.json"
    _write_json(path, rec)
    return path


def recent_captures(limit: int = 5) -> list[dict[str, Any]]:
    """Newest-first."""
    try:
        files = sorted(CAPTURE_DIR.glob("*.json"), reverse=True)[:limit]
    except Exception:  # noqa: BLE001
        return []
    out: list[dict[str, Any]] = []
    for f in files:
        doc = _read_json(f, None)
        if isinstance(doc, dict):
            out.append(doc)
    return out


# ---------------------------------------------------------------------------
# Rendering — an engineer reads a hop table, not raw command output
# ---------------------------------------------------------------------------


def render(rec: dict[str, Any], baseline: dict[str, Any] | None = None) -> str:
    """Render one capture as a hop table with a verdict and a baseline diff."""
    lines: list[str] = []
    v = rec.get("verdict") or {}
    lines.append(f"WAN PATH  {rec.get('startedAt')}  (reason: {rec.get('reason')})")
    head = f"VERDICT: {v.get('code', '?')} - {v.get('summary', '')}"
    if v.get("breakAfterIp"):
        head += (f"\n         the path stops after hop {v['breakAfterHop']} "
                 f"({v['breakAfterIp']}); the baseline gets further")
    lines.append(head)
    if rec.get("truncated"):
        lines.append("NOTE: capture hit its time budget - some probes were skipped")
    lines.append("")

    gw = rec.get("gateway")
    if gw:
        state = "alive" if gw.get("alive") else "NO REPLY"
        lines.append(f"  gateway  {gw.get('target', ''):<22} {state:<9} "
                     f"loss {gw.get('loss_pct')}%")
    dns = rec.get("dns")
    if dns:
        lines.append(f"  dns      {dns.get('name', ''):<22} "
                     f"{'ok' if dns.get('ok') else 'FAIL':<9} {dns.get('error') or ''}")
    for c in rec.get("controls") or []:
        lines.append(f"  tcp/443  {c.get('target', ''):<22} "
                     f"{'ok' if c.get('ok') else 'FAIL':<9} {c.get('error') or ''}")
    dc = rec.get("dashboardControl")
    if dc:
        lines.append(f"  tcp/443  {dc.get('target', ''):<22} "
                     f"{'ok' if dc.get('ok') else 'FAIL':<9} "
                     f"{dc.get('error') or ''}  (dashboard)")
    lines.append(f"  icmp to internet: {'yes' if rec.get('icmpInternetOk') else 'NO'}")
    lines.append("")

    base = baseline or {}
    by_mode = {str(t.get("mode")): t for t in (rec.get("traces") or [])}
    if by_mode:
        lines.append(f"  {'hop':>3}  {'icmp':<22} {'tcp/443':<22} baseline")
        max_hop = max(
            (h["hop"] for t in by_mode.values() for h in (t.get("hops") or [])),
            default=0,
        )
        base_icmp = ((base.get("modes") or {}).get("icmp") or {}).get("hop_ips") or {}
        for n in range(1, max_hop + 1):
            cells = []
            for mode in ("icmp", "tcp443"):
                t = by_mode.get(mode)
                hop = next(
                    (h for h in ((t or {}).get("hops") or []) if h["hop"] == n), None
                )
                if hop is None:
                    cells.append("")
                elif hop.get("ip"):
                    cells.append(f"{hop['ip']} {hop.get('rtt_ms')}ms")
                else:
                    cells.append("*")
            known = base_icmp.get(str(n)) or []
            marker = ""
            if v.get("breakAfterHop") == n:
                marker = "  <- PATH ENDS HERE"
            lines.append(f"  {n:>3}  {cells[0]:<22} {cells[1]:<22} "
                         f"{'|'.join(known)}{marker}")
    for d in rec.get("diffs") or []:
        for n in d.get("new_ips") or []:
            lines.append(f"  note: {d['mode']} hop {n['hop']} is {n['ip']}, "
                         f"baseline saw {'|'.join(n['baseline'])} (reroute)")
    if not (base.get("modes") or {}):
        lines.append("")
        lines.append("  NOTE: no baseline captured yet - stars below are not "
                     "interpretable until this site has a known-good path on file.")
    return "\n".join(lines)
