# lib/trunk.sh — 802.1Q VLAN trunk monitoring setup.
#
# Plug the sensor into a switch TRUNK port and monitor many VLANs from one box.
# We add a VLAN sub-interface (eth0.<id>) per VLAN via netplan; the collector
# poller then scans each like any NIC and tags the data with its VLAN (the
# scan's vlan_id/parent_interface, see scan.py _vlan_of).
#
# Hybrid detect-then-edit: sniff the 802.1Q tags on the trunk (in the collector
# container, which has tshark + host networking), propose the VLANs seen, let the
# operator add/remove. DHCP per VLAN by default — crucially with routes OFF so a
# monitoring VLAN can NEVER steal the box's uplink/default route — plus optional
# static IPs for VLANs with no DHCP.
#
# Source AFTER common.sh, paths.sh, envfile.sh.

[[ -n "${_NETMON_TRUNK_SH:-}" ]] && return 0
_NETMON_TRUNK_SH=1

NETMON_VLAN_NETPLAN="${NETMON_VLAN_NETPLAN:-/etc/netplan/60-netmon-vlans.yaml}"

# docker compose invocation (mirrors scripts/netmon-checkin.sh).
_trunk_dc() {
    if id -nG 2>/dev/null | tr ' ' '\n' | grep -qx docker; then
        docker compose "$@"
    else
        $SUDO docker compose "$@"
    fi
}

# A sensible default parent NIC: the interface owning the default route, else the
# first non-loopback/virtual NIC.
_trunk_default_parent() {
    local dev
    dev="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
    if [[ -z "$dev" ]]; then
        dev="$(ip -o link show 2>/dev/null | awk -F': ' '{print $2}' \
            | grep -vE '^(lo|docker|br-|veth|virbr|tun|tap)' | head -1)"
    fi
    printf '%s' "$dev"
}

# Does the default route ride this interface (i.e. it's the box's uplink)?
_trunk_is_uplink() {
    local parent="$1"
    ip route show default 2>/dev/null | grep -qE "dev[[:space:]]+${parent}([[:space:]]|$)"
}

# Sniff VLAN tags on the parent via the collector container; echo comma-sep ids.
# Returns non-zero (no output) if the collector container isn't running.
_trunk_detect() {
    local parent="$1"
    if ! _trunk_dc ps --status running 2>/dev/null | grep -q netmon-collector; then
        return 1
    fi
    _trunk_dc exec -T collector python -m collector detect-vlans "$parent" --seconds 8 \
        2>/dev/null | tr -d '\r'
}

# Write the netplan vlans: stanza from a VLAN list + optional statics map.
# statics: "30:10.0.30.5/24,40:10.0.40.5/24" (vlan:cidr; DHCP for the rest).
# Defines ONLY the VLAN sub-interfaces — never the parent — so the box's existing
# uplink config is left completely untouched. Echoes the file path.
generate_vlan_netplan() {
    local parent="$1" vlans="$2" statics="${3:-}"
    local f="$NETMON_VLAN_NETPLAN"
    local tmp; tmp="$(mktemp)"
    {
        echo "# Generated by 'netmon-wizard trunk' — VLAN monitoring sub-interfaces."
        echo "# Each sub-if gets an address (DHCP or static) but installs NO routes, so"
        echo "# a monitored VLAN can never hijack the box's real uplink/default route."
        echo "# Edit via the wizard, not by hand:  sudo netmon-wizard trunk"
        echo "network:"
        echo "  version: 2"
        echo "  vlans:"
        local vid cidr pair
        for vid in ${vlans//,/ }; do
            [[ "$vid" =~ ^[0-9]+$ ]] || continue
            (( vid >= 1 && vid <= 4094 )) || continue
            cidr=""
            for pair in ${statics//,/ }; do
                if [[ "$pair" == "${vid}:"* ]]; then cidr="${pair#"${vid}":}"; fi
            done
            echo "    ${parent}.${vid}:"
            echo "      id: ${vid}"
            echo "      link: ${parent}"
            if [[ -n "$cidr" ]]; then
                echo "      addresses: [${cidr}]"
            else
                echo "      dhcp4: true"
                echo "      dhcp4-overrides:"
                echo "        use-routes: false"
            fi
        done
    } > "$tmp"
    $SUDO install -m 600 -o root -g root "$tmp" "$f"
    rm -f "$tmp"
    printf '%s' "$f"
}

prompt_trunk_config() {
    echo ""
    echo "${C_INFO}=== VLAN trunk monitoring ===${C_OFF}"
    echo "Plug this sensor into a switch TRUNK port (802.1Q) and monitor many"
    echo "VLANs from one box. We add a VLAN sub-interface per VLAN; the collector"
    echo "scans each and tags the data with its VLAN."
    echo ""
    echo "The switch port must already be a trunk that allows those VLANs — the"
    echo "sensor can't reconfigure the switch."
    echo ""

    # 1. Parent interface
    local default_parent parent
    default_parent="$(current_value NETMON_TRUNK_PARENT)"
    [[ -z "$default_parent" ]] && default_parent="$(_trunk_default_parent)"
    read -r -p "Trunk parent interface [${default_parent}]: " parent || parent=""
    parent="${parent:-$default_parent}"
    if [[ -z "$parent" ]]; then warn "No interface given — trunk setup cancelled."; return 0; fi

    # 2. Uplink protection note
    echo ""
    if _trunk_is_uplink "$parent"; then
        echo "${C_WARN}Note:${C_OFF} ${parent} carries this box's default route (its uplink)."
        echo "We leave ${parent} untouched and only ADD VLAN sub-interfaces that take no"
        echo "routes, so your connection stays up. Native/untagged traffic on ${parent}"
        echo "keeps working as the management connection."
    else
        echo "${parent} is not the box's uplink, so the trunk is monitoring-only."
    fi

    # 3. Detect VLANs on the trunk
    local detected=""
    echo ""
    if prompt_yesno "Sniff the trunk to detect which VLANs are present (~8s)?" "Y"; then
        echo "  listening for 802.1Q tags on ${parent}…"
        detected="$(_trunk_detect "$parent" || true)"
        if [[ -n "$detected" ]]; then
            ok "detected VLANs: ${detected}"
        else
            warn "no tagged VLANs seen — quiet trunk, an access port, or the collector isn't running yet. Enter them manually."
        fi
    fi

    # 4. Final VLAN list (prefilled with detected, else the current value)
    local cur_vlans default_vlans vlans
    cur_vlans="$(current_value NETMON_TRUNK_VLANS)"
    default_vlans="${detected:-$cur_vlans}"
    read -r -p "VLAN IDs to monitor (comma-separated) [${default_vlans}]: " vlans || vlans=""
    vlans="${vlans:-$default_vlans}"
    vlans="$(printf '%s' "$vlans" | tr -cd '0-9,')"   # keep only digits + commas
    if [[ -z "$vlans" ]]; then warn "No VLANs given — trunk setup cancelled."; return 0; fi

    # 5. Optional static IPs
    local statics statics_in
    statics="$(current_value NETMON_TRUNK_STATICS)"
    echo ""
    echo "Every VLAN gets an address via DHCP (no routes) by default. For VLANs with"
    echo "no DHCP, set a static IP as vlan:cidr, comma-separated"
    echo "  e.g.  30:10.0.30.9/24,40:10.0.40.9/24"
    echo "Leave blank for all-DHCP."
    read -r -p "Static IPs [${statics}]: " statics_in || statics_in=""
    statics="${statics_in:-$statics}"

    # 6. Persist for re-runs + reference
    set_value NETMON_TRUNK_PARENT  "$parent"
    set_value NETMON_TRUNK_VLANS   "$vlans"
    set_value NETMON_TRUNK_STATICS "$statics"

    # 7. Generate the netplan file
    local f
    f="$(generate_vlan_netplan "$parent" "$vlans" "$statics")"
    ok "wrote ${f}"
    echo ""
    echo "Preview:"
    $SUDO sed 's/^/    /' "$f"

    # 8. Validate + apply
    echo ""
    if ! command -v netplan >/dev/null 2>&1; then
        warn "netplan not found — config written to ${f}; apply it with your network manager."
        return 0
    fi
    if $SUDO netplan generate 2>/tmp/netmon-netplan.err; then
        ok "netplan config is valid"
    else
        warn "netplan validation failed:"; $SUDO sed 's/^/    /' /tmp/netmon-netplan.err
        warn "Fix it and re-run: sudo netmon-wizard trunk"
        return 0
    fi
    if prompt_yesno "Apply now (creates the VLAN sub-interfaces)?" "Y"; then
        if $SUDO netplan apply; then
            ok "applied — VLAN sub-interfaces are up"
            echo "  the collector discovers + scans them within a poll tick (~30s)."
        else
            warn "netplan apply reported an error — check 'ip -br addr' and 'journalctl -u systemd-networkd'."
        fi
    else
        echo "  (not applied — run 'sudo netplan apply' when ready)"
    fi

    echo ""
    echo "Verify with:  ./netmon interfaces     (or  ip -br addr )"
}
